export const REQUEST_PRODUCTS = 'REQUEST_PRODUCTS';
export const RECEIVE_PRODUCTS  = 'RECEIVE_PRODUCTS';
export const RECEIVE_PRODUCT_DETAIL  = 'RECEIVE_PRODUCT_DETAIL';
export const RECEIVE_BASKET  = 'RECEIVE_BASKET';
export const RECEIVE_BASKET_EXTENDED  = 'RECEIVE_BASKET_EXTENDED';
export const ADD_TO_BASKET  = 'ADD_TO_BASKET';
export const REMOVE_FROM_BASKET  = 'REMOVE_FROM_BASKET';